name: proABC-2
channels:
  - bioconda
  - bioconda/label/cf201901
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.74
  - codecov=2.0.15
  - coverage=4.5.4
  - hmmer=3.2.1
  - igblast=1.5.0
  - numpy=1.17.2
  - pandas=0.25.1
  - python=3.6.9
  - tensorflow=1.14.0