name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          load: true # Important: this allows you to load the built image into Docker's local image store
          context: .
          target: test
          tags: proabc2:test

      - name: Run tests
        run: >
          docker run
          -v ${PWD}/coverage-report:/opt/software/proABC-2/coverage-report
          --rm
          proabc2:test
          conda run -n proABC-2 pytest --cov --cov-report xml:/opt/software/proABC-2/coverage-report/coverage.xml --cov-append -vv --hypothesis-show-statistics

      # - uses: codacy/codacy-coverage-reporter-action@v1
      #   with:
      #     project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
      #     coverage-reports: ./coverage-report/coverage.xml